### ISSUE TITLE
Do not print out client warning so many times

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-cli#120]
```
╰─± deis register deis.foo.io
!    WARNING: Client and server API versions do not match. Please consider upgrading.
!    Client version: 2.0
!    Server version: 2.1
username: admin
password:
password (confirm):
email:
!    WARNING: Client and server API versions do not match. Please consider upgrading.
!    Client version: 2.0
!    Server version: 2.1
Registered admin
!    WARNING: Client and server API versions do not match. Please consider upgrading.
!    Client version: 2.0
!    Server version: 2.1
Logged in as admin
```

We should only warn the first time the command is executed.

**Comment by rimusz** [comment]
👍

**Comment by bacongobbler** [comment]
So to identify those three, the first one is for a pre-trip check to ensure the controller is up, the second is when registering the user and the third is when logging in. We make three separate requests to the controller in this command, but agree let's only do this on the first check.

**Comment by Joshua-Anderson** [comment]
These errors are generated by api requests, and if they occur, they're logged. The problem is that there is basically no way to check if the error has already previously occurred.

The easiest solution would be: have only connection test return the api-mismatch error, and to run it before every CLI command that interacts with the API.
