### ISSUE TITLE
Can't install Deis-cli

### ISSUE THREAD

**Issue by arkkanoid** [deis/workflow-cli#71]
It seems that the bintray link is broken.

    curl -sSL http://deis.io/deis-cli/install-v2.sh | bash
    There doesn't seem to be a version of deis avaiable at https://bintray.com/deis/deisci/deis/_latestVersion

**Comment by bacongobbler** [comment]
`curl`ing https://bintray.com/deis/deisci/deis/_latestVersion seems to be giving a 302 so it looks like we just need to follow the link.

**Comment by bacongobbler** [comment]
That didn't work either. I'll look further into this.

**Comment by bacongobbler** [comment]
The problem is that we do not have any dev builds due to clearing them out to unblock bintray rate-limiting us last week. We're using their service incorrectly (not allowed to use bintray for dev builds) so we're going to have to move back to S3. For now I just filed #72 so we can get at least one dev version up on bintray until we do the migration.
